# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Audi Liew’s Folio
description: The book for Mr. Audi Liew
baseurl: "" # the subpath of your site, e.g. /blog
lang: en
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Markdown settings
destination: __build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
  #syntax_highlighter: rouge

collections:
  works:
    output: true

defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: caseStudy
      namespace: caseStudyView
      pageType: website

# Build settings
keep_files: 
  - css
  - img
  - img_source
  - js
  - vid
exclude:
  - _assets_src
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - NOTES.md
  - CNAME
  - node_modules
  - gulpfile.js

compress_html:
  clippings: all #clips all "safe" items